DROP DATABASE if EXISTS dagss ;
CREATE DATABASE dagss;
Use dagss;


REVOKE ALL PRIVILEGES ON `dagss`.* FROM 'dagss'@'localhost';

GRANT ALL PRIVILEGES ON `dagss`.* TO 'dagss'@'localhost' WITH GRANT OPTION;



CREATE TABLE `ADMINISTRADOR` (
  `ID` bigint(20) NOT NULL,
  `FECHAALTA` datetime DEFAULT NULL,
  `LOGIN` varchar(25) DEFAULT NULL,
  `NOMBRE` varchar(75) DEFAULT NULL,
  `PASSWORD` varchar(64) DEFAULT NULL,
  `TIPO_USUARIO` varchar(20) DEFAULT NULL,
  `ULTIMOACCESO` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `ADMINISTRADOR`
--

INSERT INTO `ADMINISTRADOR` (`ID`, `FECHAALTA`, `LOGIN`, `NOMBRE`, `PASSWORD`, `TIPO_USUARIO`, `ULTIMOACCESO`) VALUES
(1, '2017-11-11 01:04:42', 'admin', 'Administrador inicial', 'ggm44T97GWJ6Rryx3do4yvl1bZ+gmUfG', 'ADMINISTRADOR', '2018-01-14 04:33:44');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `CENTROSALUD`
--

CREATE TABLE `CENTROSALUD` (
  `ID` bigint(20) NOT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `TELEFONO` varchar(9) DEFAULT NULL, 
  `CODIGOPOSTAL` varchar(5) NOT NULL,
  `DOMICILIO` varchar(75) NOT NULL,
  `LOCALIDAD` varchar(30) NOT NULL,
  `PROVINCIA` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `CENTROSALUD`
--

INSERT INTO `CENTROSALUD` (`ID`, `NOMBRE`, `TELEFONO`, `CODIGOPOSTAL`, `DOMICILIO`, `LOCALIDAD`, `PROVINCIA`) VALUES
(1, 'Centro salud pepe', '988888888', '12345', 'C/. Pepe, nº 3', 'Ourense', 'Ourense');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `CITA`
--

CREATE TABLE `CITA` (
  `ID` bigint(20) NOT NULL,
  `DURACION` int(11) DEFAULT NULL,
  `ESTADO` varchar(255) DEFAULT NULL,
  `FECHA` date DEFAULT NULL,
  `HORA` time DEFAULT NULL,
  `MEDICO_ID` bigint(20) DEFAULT NULL,
  `PACIENTE_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `CITA`
--

INSERT INTO `CITA` (`ID`, `DURACION`, `ESTADO`, `FECHA`, `HORA`, `MEDICO_ID`, `PACIENTE_ID`) VALUES
(1, 15, 'PLANIFICADA', '2017-11-23', '09:00:00', 2, 3),
(2, 15, 'PLANIFICADA', '2018-01-14', '07:28:17', 2, 3);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `FARMACIA`
--

CREATE TABLE `FARMACIA` (
  `ID` bigint(20) NOT NULL,
  `FECHAALTA` datetime DEFAULT NULL,
  `NIF` varchar(9) NOT NULL,
  `NOMBREFARMACIA` varchar(75) NOT NULL,
  `PASSWORD` varchar(64) DEFAULT NULL,
  `TIPO_USUARIO` varchar(20) DEFAULT NULL,
  `ULTIMOACCESO` datetime DEFAULT NULL,
  `CODIGOPOSTAL` varchar(5) NOT NULL,
  `DOMICILIO` varchar(75) NOT NULL,
  `LOCALIDAD` varchar(30) NOT NULL,
  `PROVINCIA` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `FARMACIA`
--

INSERT INTO `FARMACIA` (`ID`, `FECHAALTA`, `NIF`, `NOMBREFARMACIA`, `PASSWORD`, `TIPO_USUARIO`, `ULTIMOACCESO`, `CODIGOPOSTAL`, `DOMICILIO`, `LOCALIDAD`, `PROVINCIA`) VALUES
(4, '2017-11-11 01:04:42', '33333333C', 'Farmacia de prueba', '/QpUw+ZRH3ndoNb3N4gRpT5cz0C7pT9v', 'FARMACIA', '2018-01-14 04:36:16', '12345', 'C/. Farmacia, nº 2, 4º N', 'Coruña', 'Coruña');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `MEDICAMENTO`
--

CREATE TABLE `MEDICAMENTO` (
  `ID` bigint(20) NOT NULL,
  `FABRICANTE` varchar(50) NOT NULL,
  `FAMILIA` varchar(50) NOT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `NUMERODOSIS` int(11) DEFAULT NULL,
  `PRINCIPIOACTIVO` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `MEDICAMENTO`
--

INSERT INTO `MEDICAMENTO` (`ID`, `FABRICANTE`, `FAMILIA`, `NOMBRE`, `NUMERODOSIS`, `PRINCIPIOACTIVO`) VALUES
(1, 'cataluña', 'psoe', 'izetaton', 2, 'izetaton');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `MEDICO`
--

CREATE TABLE `MEDICO` (
  `ID` bigint(20) NOT NULL,
  `APELLIDOS` varchar(50) NOT NULL,
  `DNI` varchar(9) NOT NULL,
  `EMAIL` varchar(25) DEFAULT NULL,
  `FECHAALTA` datetime DEFAULT NULL,
  `NOMBRE` varchar(30) NOT NULL,
  `NUMEROCOLEGIADO` varchar(10) NOT NULL,
  `PASSWORD` varchar(64) DEFAULT NULL,
  `TELEFONO` varchar(9) DEFAULT NULL,
  `TIPO_USUARIO` varchar(20) DEFAULT NULL,
  `ULTIMOACCESO` datetime DEFAULT NULL,
  `CENTROSALUD_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `MEDICO`
--

INSERT INTO `MEDICO` (`ID`, `APELLIDOS`, `DNI`, `EMAIL`, `FECHAALTA`, `NOMBRE`, `NUMEROCOLEGIADO`, `PASSWORD`, `TELEFONO`, `TIPO_USUARIO`, `ULTIMOACCESO`, `CENTROSALUD_ID`) VALUES
(2, 'Gomez Gomez', '11111111A', 'a@a.com', '2017-11-11 01:04:42', 'Antonio', '11111', 'lUTQ2zg2voe4Z5OqpITFIjcBziNH10d6', '988123456', 'MEDICO', '2018-01-14 04:29:13', 1),
(101, 'Randomez', '12345678Z', 'c@c.com', '2018-01-14 04:25:27', 'Random', '1', 'a9m+HpXvaPKRQiWj2VM/VlpT7aU2Bept', '665432575', 'MEDICO', '2018-01-14 04:25:27', 1);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `PACIENTE`
--

CREATE TABLE `PACIENTE` (
  `ID` bigint(20) NOT NULL,
  `APELLIDOS` varchar(50) NOT NULL,
  `DNI` varchar(9) NOT NULL,
  `EMAIL` varchar(25) DEFAULT NULL,
  `FECHAALTA` datetime DEFAULT NULL,
  `NOMBRE` varchar(30) NOT NULL,
  `NUMEROSEGURIDADSOCIAL` varchar(13) NOT NULL,
  `NUMEROTARJETASANITARIA` varchar(10) NOT NULL,
  `PASSWORD` varchar(64) DEFAULT NULL,
  `TELEFONO` varchar(9) DEFAULT NULL,
  `TIPO_USUARIO` varchar(20) DEFAULT NULL,
  `ULTIMOACCESO` datetime DEFAULT NULL,
  `CODIGOPOSTAL` varchar(5) NOT NULL,
  `DOMICILIO` varchar(75) NOT NULL,
  `LOCALIDAD` varchar(30) NOT NULL,
  `PROVINCIA` varchar(30) NOT NULL,
  `MEDICO_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `PACIENTE`
--

INSERT INTO `PACIENTE` (`ID`, `APELLIDOS`, `DNI`, `EMAIL`, `FECHAALTA`, `NOMBRE`, `NUMEROSEGURIDADSOCIAL`, `NUMEROTARJETASANITARIA`, `PASSWORD`, `TELEFONO`, `TIPO_USUARIO`, `ULTIMOACCESO`, `CODIGOPOSTAL`, `DOMICILIO`, `LOCALIDAD`, `PROVINCIA`, `MEDICO_ID`) VALUES
(3, 'Benito Carmona', '22222222B', 'b@b.com', '2017-11-11 01:04:42', 'Ana', '2222222222222', '2222222222', 'auJIfVxFAN0IKkDVovGmzfUENiABIC5g', '981123456', 'PACIENTE', '2017-11-11 01:04:42', '12345', 'C/. Benito, nº 2, 4º N', 'Coruña', 'Coruña', 2);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `PRESCRIPCION`
--

CREATE TABLE `PRESCRIPCION` (
  `ID` bigint(20) NOT NULL,
  `DOSIS` int(11) DEFAULT NULL,
  `FECHAFIN` date DEFAULT NULL,
  `FECHAINICIO` date DEFAULT NULL,
  `INDICACIONES` varchar(255) DEFAULT NULL,
  `MEDICAMENTO_ID` bigint(20) DEFAULT NULL,
  `MEDICO_ID` bigint(20) DEFAULT NULL,
  `PACIENTE_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `PRESCRIPCION`
--

INSERT INTO `PRESCRIPCION` (`ID`, `DOSIS`, `FECHAFIN`, `FECHAINICIO`, `INDICACIONES`, `MEDICAMENTO_ID`, `MEDICO_ID`, `PACIENTE_ID`) VALUES
(1, 1, '2018-01-18', '2018-01-03', 'jhggjhg', 1, 2, 3);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `RECETA`
--

CREATE TABLE `RECETA` (
  `ID` bigint(20) NOT NULL,
  `CANTIDAD` int(11) DEFAULT NULL,
  `ESTADORECETA` varchar(20) DEFAULT NULL,
  `FINVALIDEZ` date DEFAULT NULL,
  `INICIOVALIDEZ` date DEFAULT NULL,
  `FARMACIADISPENSADORA_ID` bigint(20) DEFAULT NULL,
  `PRESCRIPCION_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `RECETA`
--

INSERT INTO `RECETA` (`ID`, `CANTIDAD`, `ESTADORECETA`, `FINVALIDEZ`, `INICIOVALIDEZ`, `FARMACIADISPENSADORA_ID`, `PRESCRIPCION_ID`) VALUES
(1, 1, 'GENERADA', '2018-01-25', '2018-01-24', 4, 1),
(2, 2, 'SERVIDA', '2018-01-03', '2018-01-15', NULL, 1);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `USUARIO_GEN`
--

CREATE TABLE `USUARIO_GEN` (
  `GEN_NAME` varchar(50) NOT NULL,
  `GEN_VAL` decimal(38,0) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `USUARIO_GEN`
--

INSERT INTO `USUARIO_GEN` (`GEN_NAME`, `GEN_VAL`) VALUES
('USUARIO_GEN', '101');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `ADMINISTRADOR`
--
ALTER TABLE `ADMINISTRADOR`
  ADD PRIMARY KEY (`ID`);

--
-- Indices de la tabla `CENTROSALUD`
--
ALTER TABLE `CENTROSALUD`
  ADD PRIMARY KEY (`ID`);

--
-- Indices de la tabla `CITA`
--
ALTER TABLE `CITA`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_CITA_PACIENTE_ID` (`PACIENTE_ID`),
  ADD KEY `FK_CITA_MEDICO_ID` (`MEDICO_ID`);

--
-- Indices de la tabla `FARMACIA`
--
ALTER TABLE `FARMACIA`
  ADD PRIMARY KEY (`ID`);

--
-- Indices de la tabla `MEDICAMENTO`
--
ALTER TABLE `MEDICAMENTO`
  ADD PRIMARY KEY (`ID`);

--
-- Indices de la tabla `MEDICO`
--
ALTER TABLE `MEDICO`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_MEDICO_CENTROSALUD_ID` (`CENTROSALUD_ID`);

--
-- Indices de la tabla `PACIENTE`
--
ALTER TABLE `PACIENTE`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_PACIENTE_MEDICO_ID` (`MEDICO_ID`);

--
-- Indices de la tabla `PRESCRIPCION`
--
ALTER TABLE `PRESCRIPCION`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_PRESCRIPCION_MEDICO_ID` (`MEDICO_ID`),
  ADD KEY `FK_PRESCRIPCION_PACIENTE_ID` (`PACIENTE_ID`),
  ADD KEY `FK_PRESCRIPCION_MEDICAMENTO_ID` (`MEDICAMENTO_ID`);

--
-- Indices de la tabla `RECETA`
--
ALTER TABLE `RECETA`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_RECETA_FARMACIADISPENSADORA_ID` (`FARMACIADISPENSADORA_ID`),
  ADD KEY `FK_RECETA_PRESCRIPCION_ID` (`PRESCRIPCION_ID`);

--
-- Indices de la tabla `USUARIO_GEN`
--
ALTER TABLE `USUARIO_GEN`
  ADD PRIMARY KEY (`GEN_NAME`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `CENTROSALUD`
--
ALTER TABLE `CENTROSALUD`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT de la tabla `CITA`
--
ALTER TABLE `CITA`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT de la tabla `MEDICAMENTO`
--
ALTER TABLE `MEDICAMENTO`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT de la tabla `PRESCRIPCION`
--
ALTER TABLE `PRESCRIPCION`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT de la tabla `RECETA`
--
ALTER TABLE `RECETA`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `CITA`
--
ALTER TABLE `CITA`
  ADD CONSTRAINT `FK_CITA_MEDICO_ID` FOREIGN KEY (`MEDICO_ID`) REFERENCES `MEDICO` (`ID`),
  ADD CONSTRAINT `FK_CITA_PACIENTE_ID` FOREIGN KEY (`PACIENTE_ID`) REFERENCES `PACIENTE` (`ID`);

--
-- Filtros para la tabla `MEDICO`
--
ALTER TABLE `MEDICO`
  ADD CONSTRAINT `FK_MEDICO_CENTROSALUD_ID` FOREIGN KEY (`CENTROSALUD_ID`) REFERENCES `CENTROSALUD` (`ID`);

--
-- Filtros para la tabla `PACIENTE`
--
ALTER TABLE `PACIENTE`
  ADD CONSTRAINT `FK_PACIENTE_MEDICO_ID` FOREIGN KEY (`MEDICO_ID`) REFERENCES `MEDICO` (`ID`);

--
-- Filtros para la tabla `PRESCRIPCION`
--
ALTER TABLE `PRESCRIPCION`
  ADD CONSTRAINT `FK_PRESCRIPCION_MEDICAMENTO_ID` FOREIGN KEY (`MEDICAMENTO_ID`) REFERENCES `MEDICAMENTO` (`ID`),
  ADD CONSTRAINT `FK_PRESCRIPCION_MEDICO_ID` FOREIGN KEY (`MEDICO_ID`) REFERENCES `MEDICO` (`ID`),
  ADD CONSTRAINT `FK_PRESCRIPCION_PACIENTE_ID` FOREIGN KEY (`PACIENTE_ID`) REFERENCES `PACIENTE` (`ID`);

--
-- Filtros para la tabla `RECETA`
--
ALTER TABLE `RECETA`
  ADD CONSTRAINT `FK_RECETA_FARMACIADISPENSADORA_ID` FOREIGN KEY (`FARMACIADISPENSADORA_ID`) REFERENCES `FARMACIA` (`ID`),
  ADD CONSTRAINT `FK_RECETA_PRESCRIPCION_ID` FOREIGN KEY (`PRESCRIPCION_ID`) REFERENCES `PRESCRIPCION` (`ID`);
COMMIT;
